name: Deploy Hexo

on:
  push:
    branches:
      - hexo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy to GitHub Pages
        run: npx hexo deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
